name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
#
#      - name: Install dependencies
#        run: npm install  # Or whatever command you use to install dependencies
#
#      - name: Build
#        run: npm run build  # Or whatever command you use to build your project

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /
            cd /www/wwwroot/namaste-bali-trans
            sudo git pull origin main  # Update your project from GitHub
            source build.sh
