name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install  # Or whatever command you use to install dependencies

      - name: Build
        run: npm run build  # Or whatever command you use to build your project

      - name: Deploy to VPS
        run: |
          sshpass -p ${{ secrets.VPS_PASSWORD }} ssh ${{ secrets.VPS_USERNAME }}:${{ secrets.VPS_PASSWORD }}@${{ secrets.VPS_HOST }} "sudo su && cd /www/wwwroot/namaste-bali-trans && git pull origin main && source build.sh"
